name: Deploy SNMP Server
 
on:
  push:
    branches:
      - main 
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH for server
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $REMOTE_SERVER_IP >> ~/.ssh/known_hosts
 
      - name: Deploy to SNMP Server
        run: |
          ssh user@$REMOTE_SERVER_IP "cd /path/to/snmpsetup && git pull && ./deploy.sh"

 
