name: Run Azure Script Every 24 Hours

on:
  schedule:
    ##- cron: '0 0 * * *' 
  workflow_dispatch:  

env:
  TENANT_ID: ${{ secrets.TENANT_ID }}  
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}

jobs:
  run-python-script:
    runs-on: ubuntu-latest  
    environment: Production
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests azure-identity 
        
    - name: Debug environment variables (for testing)
      run: |
        echo "TENANT_ID: $TENANT_ID"
        echo "CLIENT_ID: $CLIENT_ID"
        echo "CLIENT_SECRET: $CLIENT_SECRET"
        echo "SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN"

    - name: Run the Azure Script
      run: python Runbooks/PythonscriptforAzureAD.py  
      env:
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SPLUNK_HEC_TOKEN: ${{ secrets.SPLUNK_HEC_TOKEN }}
